=== CycriLabs/ws-ctrl/schemas/use-case.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Context": {
      "type": "object",
      "additionalProperties": true
    },
    "UseCaseState": {
      "type": "string",
      "enum": ["ENABLED", "DISABLED", "INITIAL", "HIDDEN"]
    },
    "UseCaseStep": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["FORMULA", "COMMAND", "EXECUTOR", "USE_CASE", "PROMPT"]
        },
        "description": {
          "type": "string"
        },
        "loop": {
          "type": "object",
          "properties": {
            "list": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["list", "name"]
        },
        "inputFile": {
          "type": "string"
        },
        "outputFile": {
          "type": "string"
        },
        "abortIf": {
          "type": "string"
        },
        "skipIf": {
          "type": "string"
        },
        "catchErrors": {
          "type": "boolean"
        },
        "useCase": {
          "type": "string"
        },
        "formula": {
          "type": "string"
        },
        "command": {
          "type": "string"
        },
        "executor": {
          "type": "string"
        },
        "resultVariable": {
          "type": "string"
        },
        "context": {
          "$ref": "#/definitions/Context"
        }
      },
      "required": ["type"]
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "The unique identifier of the entity"
    },
    "name": {
      "type": "string",
      "description": "The display name used throughout all prompts"
    },
    "description": {
      "type": "string"
    },
    "state": {
      "$ref": "#/definitions/UseCaseState"
    },
    "steps": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UseCaseStep"
      }
    }
  },
  "required": ["id", "name", "steps"]
}

=== CycriLabs/ws-ctrl/dist/templates/config/use-cases/init.json
{
  "$schema": "https://gist.githubusercontent.com/MarcScheib/eaed8888c0f47a4d52b7f938c70c2355/raw/8734e53ec76e085fcb559c3cdb394a5ea84e8ca0/use-case.schema.json",
  "id": "init",
  "name": "Init use-case",
  "description": "The init use-case is called from the init command",
  "state": "INITIAL",
  "steps": [
    {
      "type": "PROMPT",
      "context": {
        "name": "clone",
        "message": "Do you want to clone repositories initially?",
        "type": "toggle"
      }
    },
    {
      "type": "USE_CASE",
      "description": "Do you want to clone repositories initially?",
      "skipIf": "clone === false",
      "useCase": "clone-repositories"
    }
  ]
}

=== CycriLabs/ws-ctrl/dist/templates/config/use-cases/sync.json
{
  "$schema": "https://gist.githubusercontent.com/MarcScheib/eaed8888c0f47a4d52b7f938c70c2355/raw/8734e53ec76e085fcb559c3cdb394a5ea84e8ca0/use-case.schema.json",
  "id": "sync",
  "name": "Sync use-case",
  "description": "The sync use-case is called from the sync command",
  "state": "HIDDEN",
  "steps": []
}

=== CycriLabs/ws-ctrl/assets/templates/config/use-cases/init.json
{
  "$schema": "https://raw.githubusercontent.com/CycriLabs/ws-ctrl/refs/heads/main/schemas/use-case.schema.json",
  "id": "init",
  "name": "Init use-case",
  "description": "The init use-case is called from the init command",
  "state": "INITIAL",
  "steps": [
    {
      "type": "PROMPT",
      "context": {
        "name": "clone",
        "message": "Do you want to clone repositories initially?",
        "type": "toggle"
      }
    },
    {
      "type": "USE_CASE",
      "description": "Do you want to clone repositories initially?",
      "skipIf": "clone === false",
      "useCase": "clone-repositories"
    }
  ]
}

=== CycriLabs/ws-ctrl/assets/templates/config/use-cases/pull-repositories.json
{
  "$schema": "https://gist.githubusercontent.com/MarcScheib/eaed8888c0f47a4d52b7f938c70c2355/raw/8734e53ec76e085fcb559c3cdb394a5ea84e8ca0/use-case.schema.json",
  "id": "pull-repositories",
  "name": "Pull repositories",
  "description": "This use case pulls repositories.",
  "steps": [
    {
      "type": "PROMPT",
      "description": "Select the repositories to pull",
      "context": {
        "name": "repositories",
        "message": "Select the repositories",
        "type": "multiselect",
        "entityKey": "REPOSITORIES"
      }
    },
    {
      "type": "COMMAND",
      "description": "Pull repositories",
      "loop": {
        "list": "repositories",
        "name": "repository"
      },
      "command": "`git -C ${WORKING_DIR}/${repository.alias} pull`"
    }
  ]
}

=== CycriLabs/ws-ctrl/dist/templates/config/use-cases/check-requirements.json
{
  "$schema": "https://gist.githubusercontent.com/MarcScheib/eaed8888c0f47a4d52b7f938c70c2355/raw/8734e53ec76e085fcb559c3cdb394a5ea84e8ca0/use-case.schema.json",
  "id": "check-requirements",
  "name": "Check requirements",
  "description": "This use case checks the requirements to develop locally.",
  "steps": [
    {
      "type": "COMMAND",
      "description": "Execute commands",
      "context": {
        "commands": [
          "git --version",
          "node --version",
          "npm --version",
          "docker --version",
          "docker compose version"
        ]
      },
      "loop": {
        "list": "STEP.context.commands",
        "name": "command"
      },
      "command": "`${command}`"
    }
  ]
}

=== CycriLabs/ws-ctrl/assets/templates/config/use-cases/check-requirements.json
{
  "$schema": "https://raw.githubusercontent.com/CycriLabs/ws-ctrl/refs/heads/main/schemas/use-case.schema.json",
  "id": "check-requirements",
  "name": "Check requirements",
  "description": "This use case checks the requirements to develop locally.",
  "steps": [
    {
      "type": "FORMULA",
      "description": "Print OS info",
      "formula": "console.log(`Running on ${OS}`)"
    },
    {
      "type": "COMMAND",
      "description": "Execute commands",
      "context": {
        "commands": [
          "git --version",
          "node --version",
          "npm --version",
          "docker --version",
          "docker compose version"
        ]
      },
      "loop": {
        "list": "STEP.context.commands",
        "name": "command"
      },
      "command": "`${command}`"
    }
  ]
}

=== CycriLabs/ws-ctrl/assets/templates/config/use-cases/list-containers.json
{
  "$schema": "https://raw.githubusercontent.com/CycriLabs/ws-ctrl/refs/heads/main/schemas/use-case.schema.json",
  "id": "list-containers",
  "name": "List containers",
  "description": "List containers.",
  "steps": [
    {
      "type": "COMMAND",
      "description": "List all running docker containers",
      "command": "`docker compose ps`"
    }
  ]
}

=== CycriLabs/ws-ctrl/assets/templates/config/use-cases/clone-repositories.json
{
  "$schema": "https://raw.githubusercontent.com/CycriLabs/ws-ctrl/refs/heads/main/schemas/use-case.schema.json",
  "id": "clone-repositories",
  "name": "Clone repositories",
  "description": "This use case clones repositories.",
  "steps": [
    {
      "type": "PROMPT",
      "description": "Select the repositories to clones",
      "context": {
        "name": "repositories",
        "message": "Select the repositories",
        "type": "multiselect",
        "entityKey": "REPOSITORIES"
      }
    },
    {
      "type": "COMMAND",
      "description": "Clone repositories",
      "loop": {
        "list": "repositories",
        "name": "repository"
      },
      "command": "`git clone -b develop ${repository.url} ${WORKING_DIR}/${repository.alias}`"
    }
  ]
}
